### ISSUE TITLE
Bulk email subscription

### ISSUE THREAD

**Issue by guerriky** [vatps/mailchimp-rest-api#2]
Hi,
well, this isn't an actual issue, I just can't seem to find any way to contact you personally.

I just wanted to know if your code supports the "bulk" push of subscribers email.

It works if you make one request per email, but I don't think that's how it's supposed to be.

Are there any methods that allow me to do this?
I'm really getting into it now :)

Thanks,
Riccardo

**Comment by vatps** [comment]
Use loop or take help from https://us9.api.mailchimp.com/schema/3.0/Lists/Members/Instance.json
