### ISSUE TITLE
Result is always blank

### ISSUE THREAD

**Issue by sparky672** [vatps/mailchimp-rest-api#7]
I am following your simple example for adding a single subscriber and the `$result` is always coming back blank or empty.  I don't know what else to try.

**Comment by crg821** [comment]
Hi, 
Are you able to add subscribers to your Mailchimp account at all?, is your $data['status']== 400 ?, You can also try to print $data['detail'] as it may contain the error message. 

`

**Comment by sparky672** [comment]
> Are you able to add subscribers to your Mailchimp account at all?

Yes, but only when using my old PHP wrapper for MailChimp API version 1.  I have not tried API 2, since API 3 is all that will matter come 2017.

> is your `$data['status']` == 400 ?

It's also blank.  According to my console log, XHR status is `200`, but I believe that is just my server response of the Ajax request over to my PHP file.

> You can also try to print `$data['detail']` as it may contain the error message.

This too is blank.

**Comment by sparky672** [comment]
Never mind... it took a while before I finally realized that I was still using GET instead of POST.  Since `$_GET` is null, the API was getting NULL values.
